import { type IconItem } from "@/types/icon";

// Auto-generated by SVG → TS Map - Sample Atlas Icons
export const iconMap: Record<string, string> = {
  "abacus": `<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.cls-1{fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:1.91px;}</style></defs><polyline class="cls-1" points="21.55 0.52 21.55 18.66 2.46 18.66 2.46 0.52"/><rect class="cls-1" x="1.5" y="18.66" width="21" height="3.82"/><line class="cls-1" x1="2.45" y1="2.43" x2="21.55" y2="2.43"/><line class="cls-1" x1="6.27" y1="0.52" x2="6.27" y2="4.34"/><line class="cls-1" x1="9.14" y1="0.52" x2="9.14" y2="4.34"/><line class="cls-1" x1="12" y1="0.52" x2="12" y2="4.34"/><line class="cls-1" x1="2.45" y1="8.16" x2="21.55" y2="8.16"/><line class="cls-1" x1="10.09" y1="6.25" x2="10.09" y2="10.07"/><line class="cls-1" x1="12.95" y1="6.25" x2="12.95" y2="10.07"/><line class="cls-1" x1="17.73" y1="6.25" x2="17.73" y2="10.07"/><line class="cls-1" x1="2.45" y1="13.89" x2="21.55" y2="13.89"/><line class="cls-1" x1="6.27" y1="11.98" x2="6.27" y2="15.8"/><line class="cls-1" x1="9.14" y1="11.98" x2="9.14" y2="15.8"/><line class="cls-1" x1="15.82" y1="11.98" x2="15.82" y2="15.8"/></svg>`,
  "account": `<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.cls-1{fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:1.91px;}</style></defs><circle class="cls-1" cx="12" cy="7.25" r="5.73"/><path class="cls-1" d="M1.5,23.48l.37-2.05A10.3,10.3,0,0,1,12,13h0a10.3,10.3,0,0,1,10.13,8.45l.37,2.05"/></svg>`,
  "add": `<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.cls-1{fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:1.91px;}</style></defs><line class="cls-1" x1="12" y1="1.5" x2="12" y2="22.5"/><line class="cls-1" x1="1.5" y1="12" x2="22.5" y2="12"/></svg>`,
  "address-book": `<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.cls-1{fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:1.91px;}</style></defs><rect class="cls-1" x="3" y="1.5" width="15" height="21"/><line class="cls-1" x1="18" y1="3.5" x2="20.5" y2="3.5"/><line class="cls-1" x1="18" y1="7.5" x2="20.5" y2="7.5"/><line class="cls-1" x1="18" y1="11.5" x2="20.5" y2="11.5"/><line class="cls-1" x1="18" y1="15.5" x2="20.5" y2="15.5"/><line class="cls-1" x1="18" y1="19.5" x2="20.5" y2="19.5"/><circle class="cls-1" cx="10.5" cy="8.5" r="2.5"/><path class="cls-1" d="M14.13,18.5A4.29,4.29,0,0,0,10.5,16h0a4.29,4.29,0,0,0-3.63,2.5"/></svg>`,
  "air-conditioner": `<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><style>.cls-1{fill:none;stroke:currentColor;stroke-miterlimit:10;stroke-width:1.91px;}</style></defs><rect class="cls-1" x="2.5" y="2.5" width="19" height="8"/><line class="cls-1" x1="5.5" y1="14.5" x2="5.5" y2="21.5"/><line class="cls-1" x1="9.5" y1="10.5" x2="9.5" y2="15.5"/><line class="cls-1" x1="12" y1="10.5" x2="12" y2="17.5"/><line class="cls-1" x1="14.5" y1="10.5" x2="14.5" y2="15.5"/><line class="cls-1" x1="18.5" y1="14.5" x2="18.5" y2="21.5"/><polyline class="cls-1" points="8.5 19.5 5.5 16.5 2.5 19.5"/><polyline class="cls-1" points="21.5 19.5 18.5 16.5 15.5 19.5"/></svg>`
};

// Convert iconMap to IconItem format
export const atlasIcons: IconItem[] = Object.entries(iconMap).map(([key, svg]) => ({
  id: `atlas-${key}`,
  name: key.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' '),
  svg: svg,
  tags: [key.replace(/-/g, ' ')],
  style: 'outline',
  category: 'general'
}));